# Generated by Django 2.1.2 on 2018-10-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('standing_charge', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='standing charge')),
                ('minute_call_charge', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='call charge/minute')),
            ],
            options={
                'verbose_name': 'pricing rule',
                'verbose_name_plural': 'princing rules',
            },
        ),
    ]
