# Generated by Django 2.1.2 on 2018-10-13 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingrule',
            options={'verbose_name': 'pricing rule', 'verbose_name_plural': 'pricing rules'},
        ),
    ]
