# Generated by Django 2.1.2 on 2018-10-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181013_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('start', 'Call Start'), ('end', 'Call End')], max_length=5, verbose_name='record type')),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'call detail',
                'verbose_name_plural': 'calls details',
            },
        ),
    ]
