# Generated by Django 2.1.2 on 2018-10-15 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_calldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetail',
            name='destination',
            field=models.CharField(default=99999, max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numbers are allowed.', 'Invalid phone number')], verbose_name='destination phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calldetail',
            name='source',
            field=models.CharField(default='99999999999', max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numbers are allowed.', 'Invalid phone number')], verbose_name='source phone number'),
            preserve_default=False,
        ),
    ]
