# Generated by Django 2.1.2 on 2018-10-15 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181015_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetail',
            name='destination',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numbers are allowed.', 'Invalid phone number')], verbose_name='destination phone number'),
        ),
        migrations.AlterField(
            model_name='calldetail',
            name='source',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numbers are allowed.', 'Invalid phone number')], verbose_name='source phone number'),
        ),
    ]
