# Generated by Django 2.1.2 on 2018-10-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181015_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='standing charge')),
                ('detail_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_end', to='core.CallDetail')),
                ('detail_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_start', to='core.CallDetail')),
            ],
        ),
    ]
