# Generated by Django 2.1.2 on 2018-10-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='detail_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_end', to='core.CallDetail'),
        ),
        migrations.AlterField(
            model_name='call',
            name='detail_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_start', to='core.CallDetail'),
        ),
    ]
