# Generated by Django 2.1.2 on 2018-10-16 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181016_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='duration',
        ),
    ]
