# Generated by Django 2.1.2 on 2018-10-23 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181023_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetail',
            name='destination',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numbers are allowed.', 'Invalid phone number'), django.core.validators.MinLengthValidator(10)], verbose_name='destination phone number'),
        ),
        migrations.AlterField(
            model_name='calldetail',
            name='source',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numbers are allowed.', 'Invalid phone number'), django.core.validators.MinLengthValidator(10)], verbose_name='source phone number'),
        ),
    ]
