# Generated by Django 2.1.2 on 2018-10-24 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181023_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='detail_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_end', to='core.CallDetail'),
        ),
        migrations.AlterField(
            model_name='call',
            name='detail_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_start', to='core.CallDetail'),
        ),
    ]
